apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 (0ab07be)
  labels:
    io.kompose.service: employee-backend
  name: employee-backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: employee-backend
    spec:
      containers:
      - env:
        - name: CLOUD_CONFIG_URI
          value: http://configServer:9090
        - name: EUREKA_URI
          value: http://eureka:9091/eureka
        - name: ZIPKIN_URI
          value: http://zipkin:9411
        image: employee-backend:1.0-SNAPSHOT
        name: employee-backend
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
