apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: eureka
    serviceType: eureka
  name: eureka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: eureka
    spec:
      containers:
      - image: eureka:1.0-SNAPSHOT
        name: eureka
        imagePullPolicy: Never 
        ports:
        - containerPort: 9091
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
 name: eureka-entrypoint
 namespace: default
spec:
 selector:
   serviceType: eureka
 ports:
   - port: 9091
     targetPort: 9091
 type: LoadBalancer
