apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: eureka
  name: eureka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: eureka
    spec:
      containers:
      - image: eureka:1.0-SNAPSHOT
        name: eureka
        ports:
        - containerPort: 9091
        resources: {}
      restartPolicy: Always
status: {}
