apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: employee-backend
  labels:
    serviceType: employee-backend
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        serviceType: employee-backend
    spec:
      containers:
      - env:
        - name: CLOUD_CONFIG_URI
          value: http://config-server:9090
        - name: EUREKA_URI
          value: http://eureka-service:9091/eureka
        - name: ZIPKIN_URI
          value: zipkin:9411
        image: employee-backend:1.0-SNAPSHOT
        name: employee-backend
        ports:
        - containerPort: 9092
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: employee-backend-service
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 9092
  selector:
    serviceType: employee-backend
  type: LoadBalancer
status:
  loadBalancer: {}
