apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - image: eureka:1.0-SNAPSHOT
        name: eureka
        imagePullPolicy: Never
        ports:
        - containerPort: 9091
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
 name: eureka-service
spec:
 selector:
   app: eureka
 ports:
   - port: 9091
     targetPort: 9091
 type: LoadBalancer
