apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    io.kompose.service: zipkin
  name: zipkin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        io.kompose.service: zipkin
    spec:
      containers:
      - env:
        - name: STORAGE_TYPE
          value: mem
        image: openzipkin/zipkin
        name: zipkin
        ports:
        - containerPort: 9411
        resources: {}
      restartPolicy: Always
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  ports:
  - name: "9411"
    port: 9411
    targetPort: 9411
  selector:
    io.kompose.service: zipkin
status:
  loadBalancer: {}

