version: '2'

services:
  config-server:
    image: "config-server:1.0-SNAPSHOT"
    ports:
      - "9090:9090"

  eureka:
    image: "eureka:1.0-SNAPSHOT"
    ports:
      - "9091:9091"

  gateway:
    image: "gateway:1.0-SNAPSHOT"
    ports:
      - "9094:9094"
    links:
      - eureka
    environment:
      - EUREKA_URI=http://eureka:9091/eureka
      - ZIPKIN_URI=http://zipkin:9411

  employee-dashboard:
    image: "employee-dashboard:1.0-SNAPSHOT"
    ports:
      - "9093:9093"
    links:
      - eureka
      - configServer
    environment:
      - CLOUD_CONFIG_URI=http://configServer:9090
      - EUREKA_URI=http://eureka:9091/eureka
      - ZIPKIN_URI=http://zipkin:9411

  employee-backend:
    image: "employee-backend:1.0-SNAPSHOT"
    ports:
      - "9092:9092"
    depends_on:
      - eureka
      - configServer
    links:
      - eureka
      - configServer
    environment:
      - CLOUD_CONFIG_URI=http://configServer:9090
      - EUREKA_URI=http://eureka:9091/eureka
      - ZIPKIN_URI=http://zipkin:9411

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    # Environment settings are defined here https://github.com/openzipkin/zipkin/tree/1.19.0/zipkin-server#environment-variables
    environment:
      - STORAGE_TYPE=mem
      # Uncomment to disable scribe
      # - SCRIBE_ENABLED=false
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG
    ports:
      - "9411:9411"
